#!/bin/bash
# postprovision.sh — Handles cross-RG AOAI role assignment and generates env/.env.azure
set -euo pipefail

echo "=== Postprovision: configuring resources ==="

# Helper: get azd env var
get_env() {
  azd env get-value "$1" 2>/dev/null || echo ""
}

# ─── Ensure Service Principal exists for Bot App Registration ─────────────────

BOT_APP_ID=$(get_env "BOT_CLIENT_ID")
if [[ -n "$BOT_APP_ID" ]]; then
  echo "  Ensuring service principal exists for bot app ($BOT_APP_ID)..."
  if az ad sp show --id "$BOT_APP_ID" &>/dev/null; then
    echo "  Service principal already exists."
  else
    az ad sp create --id "$BOT_APP_ID" --output none
    echo "  Service principal created."
  fi
fi

# ─── Cross-RG Azure OpenAI Role Assignment ───────────────────────────────────────

CREATE_AOAI=$(get_env "CREATE_AZURE_OPENAI")
AOAI_SAME_RG=$(get_env "AOAI_SAME_RESOURCE_GROUP")

if [[ "$CREATE_AOAI" != "true" && "$AOAI_SAME_RG" != "true" ]]; then
  AOAI_RESOURCE_NAME=$(get_env "AZURE_OPENAI_RESOURCE_NAME")
  AOAI_RG=$(get_env "AZURE_OPENAI_RESOURCE_GROUP")
  AOAI_SUB=$(get_env "AZURE_OPENAI_SUBSCRIPTION")
  ACA_PRINCIPAL_ID=$(get_env "SERVICE_AGENT_PRINCIPAL_ID")

  # If azd didn't set the principal ID, try the Bicep output name
  if [[ -z "$ACA_PRINCIPAL_ID" ]]; then
    ACA_PRINCIPAL_ID=$(get_env "ACA_PRINCIPAL_ID")
  fi

  if [[ -n "$ACA_PRINCIPAL_ID" && -n "$AOAI_RESOURCE_NAME" && -n "$AOAI_RG" ]]; then
    echo "  Azure OpenAI is in a different resource group ($AOAI_RG)."
    echo "  Assigning Cognitive Services OpenAI User role to ACA managed identity..."

    SUB_ARG=""
    if [[ -n "$AOAI_SUB" ]]; then
      SUB_ARG="--subscription $AOAI_SUB"
    fi

    AOAI_FULL_ID=$(az cognitiveservices account show \
      --name "$AOAI_RESOURCE_NAME" \
      --resource-group "$AOAI_RG" \
      --query id -o tsv $SUB_ARG)

    az role assignment create \
      --role "Cognitive Services OpenAI User" \
      --assignee-object-id "$ACA_PRINCIPAL_ID" \
      --assignee-principal-type ServicePrincipal \
      --scope "$AOAI_FULL_ID" \
      --output none 2>/dev/null || true

    echo "  Role assignment complete."
  else
    echo "  Warning: Could not assign cross-RG AOAI role. Assign manually if needed."
  fi
fi

# ─── Generate env/.env.azure ─────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$ROOT_DIR/env/.env.azure"

BOT_CLIENT_ID=$(get_env "BOT_CLIENT_ID")
BOT_OBJECT_ID=$(get_env "BOT_OBJECT_ID")
BOT_TENANT_ID=$(get_env "BOT_TENANT_ID")
ACA_FQDN=$(get_env "ACA_FQDN")
AOAI_ENDPOINT=$(get_env "AZURE_OPENAI_ENDPOINT")
AOAI_DEPLOYMENT=$(get_env "AZURE_OPENAI_DEPLOYMENT")
AOAI_API_VERSION=$(get_env "AZURE_OPENAI_API_VERSION")
RESOURCE_GROUP=$(get_env "AZURE_RESOURCE_GROUP")
ACA_NAME=$(get_env "ACA_NAME")
ACR_LOGIN_SERVER=$(get_env "ACR_LOGIN_SERVER")
ACR_NAME=$(get_env "ACR_NAME")

# If ACA_FQDN not in azd env, try Bicep output name
if [[ -z "$ACA_FQDN" ]]; then
  ACA_FQDN=$(get_env "acaFqdn")
fi

# Preserve Toolkit-managed env vars before overwriting
TOOLKIT_KEYS="APP_NAME_SUFFIX TEAMS_APP_ID TEAMSFX_ENV AAD_APP_ACCESS_AS_USER_PERMISSION_ID TEAMS_APP_TENANT_ID M365_TITLE_ID M365_APP_ID"
PRESERVED_LINES=""
if [[ -f "$ENV_FILE" ]]; then
  for key in $TOOLKIT_KEYS; do
    line=$(grep "^${key}=" "$ENV_FILE" 2>/dev/null || true)
    if [[ -n "$line" ]]; then
      PRESERVED_LINES="${PRESERVED_LINES}
${line}"
    fi
  done
fi

cat > "$ENV_FILE" << EOF
# Auto-generated by azd postprovision hook
BOT_ID=$BOT_CLIENT_ID
BOT_OBJECT_ID=$BOT_OBJECT_ID
BOT_TENANT_ID=$BOT_TENANT_ID
TEAMS_APP_TENANT_ID=$BOT_TENANT_ID
BOT_ENDPOINT=https://$ACA_FQDN
BOT_DOMAIN=$ACA_FQDN
AZURE_OPENAI_ENDPOINT=$AOAI_ENDPOINT
AZURE_OPENAI_DEPLOYMENT=$AOAI_DEPLOYMENT
AZURE_OPENAI_API_VERSION=$AOAI_API_VERSION
RESOURCE_GROUP=$RESOURCE_GROUP
ACA_NAME=$ACA_NAME
EOF

if [[ -n "$ACR_LOGIN_SERVER" ]]; then
  echo "ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER" >> "$ENV_FILE"
  echo "ACR_NAME=$ACR_NAME" >> "$ENV_FILE"
fi

# Append preserved Toolkit-managed env vars
if [[ -n "$PRESERVED_LINES" ]]; then
  echo "$PRESERVED_LINES" >> "$ENV_FILE"
fi

echo "  Generated $ENV_FILE"
echo "=== Postprovision: complete ==="
